name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          user: rjsuzuki
          template: "@super-metrics"
          setup_community_templates: octocat/metrics@master:super-metrics, octocat/metrics@master:trusted-metrics+trust
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          
          # Intro
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          # Lines
          plugin_lines: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list, about
          plugin_sponsors_size: 24
          plugin_stars: yes
          plugin_stars_limit: 4
          
          # StackOverFlow options
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 8332505                           # Stackoverflow user id (required)
          plugin_stackoverflow_sections: answers-top, questions-recent # Display top answers and recent questions
          plugin_stackoverflow_limit: 2                                # Display 2 entries per section
          plugin_stackoverflow_lines: 4                                # Display 4 lines per entry
          plugin_stackoverflow_lines_snippet: 2                        # Display 2 lines in embed code snippets
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: detailed  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          plugin_achievements_ignored: octonaut # Hide "octonaut" achievement
          plugin_achievements_only: explorer    # Display only "explorer" achievement (don't use with "ignored" option)
          
          # Recent Activity
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 3
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          # Habits
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
      
          
          # Code Language Stats
          plugin_languages: yes
          plugin_languages_ignored: html, css                           # List of languages to ignore
          plugin_languages_skipped: my-test-repo                        # List of repositories to skip
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used
          plugin_languages_colors: github                               # Make most used languages orange and JavaScript red
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..." # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                                # Hides all languages less than 2%
 
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)
          plugin_languages_analysis_timeout: 15                         # Set maximum time for indepth analysis
          plugin_languages_categories: markup, programming              # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming, data # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 500                             # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 7                               # Limit recently used stats to last week
          commits_authoring: rjsuzuki@users.noreply.github.com           # Surnames or email addresses used to identify your commits
