name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          template: "@super-metrics"
          setup_community_templates: octocat/metrics@master:super-metrics, octocat/metrics@master:trusted-metrics+trust
           # StackOverFlow options
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 8332505                           # Stackoverflow user id (required)
          plugin_stackoverflow_sections: answers-top, questions-recent # Display top answers and recent questions
          plugin_stackoverflow_limit: 2                                # Display 2 entries per section
          plugin_stackoverflow_lines: 4                                # Display 4 lines per entry
          plugin_stackoverflow_lines_snippet: 2                        # Display 2 lines in embed code snippets
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: compact  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          plugin_achievements_ignored: octonaut # Hide "octonaut" achievement
          plugin_achievements_only: explorer    # Display only "explorer" achievement (don't use with "ignored" option)
          # Code Language Stats
          plugin_languages: yes
          plugin_languages_ignored: html, css                           # List of languages to ignore
          plugin_languages_skipped: my-test-repo                        # List of repositories to skip
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used
          plugin_languages_colors: "0:orange, javascript:#ff0000, ..."  # Make most used languages orange and JavaScript red
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..." # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                                # Hides all languages less than 2%
 
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)
          plugin_languages_analysis_timeout: 15                         # Set maximum time for indepth analysis
          plugin_languages_categories: programming                      # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming, data # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 500                             # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 7                               # Limit recently used stats to last week
          commits_authoring: rjsuzuki@users.noreply.github.com           # Surnames or email addresses used to identify your commits
